---
- name: This playbook is to connect to remote and restart apache2 service on ubuntu 14.2
  hosts: 192.168.56.103
  become: root
  gather_facts: true
  
  tasks:
    - name: check service is running
      service:
         name: apache2
         status: running
      register: status_of_apache2
      
    - name: run if is not running
      service:
         name: apache2
         status: service apache2 restart
      when: 'status_of_apache2.state is not running' 
